# Generated by Django 5.1 on 2024-09-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='api.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=250, null=True),
        ),
    ]
